20: call part2(), first attempt at iterating particle vector twice and removing elements
Leads expectedly to borrowing issues:

    error[E0502]: cannot borrow `*p` as mutable because it is also borrowed as immutable
       --> src/main.rs:117:3
        |
    112 |  for (i, particle) in p.iter().enumerate() {
        |                       - immutable borrow occurs here
    ...
    117 |   p.remove(0);
        |   ^ mutable borrow occurs here
    118 |  }
        |  - immutable borrow ends here

Signed-off-by: Edward Cragg <drq.11235@gmail.com>